title:              "브랜드 인사이트"
tagline:            "Brand insight"
email:              "hohehiha13@naver.com"
description:        "브랜드의 철학, 비지니스를 알아보기 위한 공간"
author:             "김은경"
baseurl:            "/"
url:                "https://eunkyung.kr"
locale:             "ko_KR"
thumbnail:          "/img/thumbnail.jpg"

# Social Profiles
instagram_username: _eunkyung13


# Build settings
markdown:           kramdown
permalink:          /:title
paginate:           5
paginate_path:      "/posts/thumbnail_1200x628px/"
plugins:
  - jekyll-paginate

disqus:
  shortname: eunkyung-kr
